version: '3.8'

services:
  pacientes-app:
    build: 
      context: .
    container_name: pacientes-app
    ports:
      - "8080:8080"
    environment:
      # Le decimos a Spring Boot que la wallet estará en la carpeta /app/wallet dentro de Docker
      - RUTA_WALLET=/app/wallet
    volumes:
      # AQUI CAMBIA LA RUTA DE LA IZQUIERDA POR LA RUTA REAL DE TU WALLET EN WINDOWS
      - C:\Users\Carlos\Documents\Wallet_Oracle:/app/wallet
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        mode: non-blocking
        max-buffer-size: 4m
        loki-retries: "3"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki